
class Actions(object):

    REGISTER_PLAYER = 'REGISTER_PLAYER'
    REGISTER_PLAYER_SUCCESS = 'REGISTER_PLAYER_SUCCESS'
    REGISTER_PLAYER_FAILURE = 'REGISTER_PLAYER_FAILURE'

    GAME_STATE = 'GAME_STATE'
    # ERRORS

    ERROR_INVALID_PLAYER = 'INVALID_PLAYER'
    ERROR_INVALID_TOKEN = 'INVALID_TOKEN'